### ISSUE TITLE
 Incorrect Suffix Handling for macOS

### ISSUE THREAD

**Issue by m-mdy-m** [devraymondsh/kivi#15]
In the current implementation of the `dll.js` file, the `suffix` for macOS (`darwin`) is incorrectly set to `"dll"`. According to the platform-specific naming conventions, macOS uses the `.dylib` extension for dynamic libraries, not `.dll`.

**Current Code:**
```javascript
let suffix;
switch (platform) {
  case "windows":
    suffix = "dll";
    break;
  case "dylib":
    suffix = "dll";
    break;
  default:
    suffix = "so";
    break;
}
```

As you can see, in the current implementation, the case for `dylib` is being handled incorrectly by setting the suffix to `"dll"`. This is a mistake because macOS uses `.dylib` for dynamic libraries, not `.dll`.

**Proposed Fix:**

The `switch` statement should be updated to correctly handle the macOS platform by using `"dylib"` for the suffix. Additionally, it would be good to handle unsupported platforms more gracefully with an error message. Here’s the updated version of the code:

```javascript
let suffix;
switch (platform) {
  case "windows":
    suffix = "dll";
    break;
  case "darwin":
    suffix = "dylib";  // Corrected from "dylib" to "darwin"
    break;
  case "linux":
    suffix = "so";
    break;
  default:
    console.error(`Platform ${platform} is not supported.`);
    throw new Error(`Unsupported platform: ${platform}`);
}
```

**Comment by devraymondsh** [comment]
Nice fix. Are you willing to submit a PR?

**Comment by m-mdy-m** [comment]
i did it :)

**Comment by devraymondsh** [comment]
Thank you for your contribution.
